// Keyboard Event teen trah ke hote hai
// ek hota hai keyUp
// ek hota hai keyDown
// aur ek hota hai keyPress

// tab index dene se koi bhi element focusable ho jata hai

const h1 = document.querySelector('h1')
const input = document.querySelector('input')

h1.addEventListener('keypress', (e) =>{
    //alag event ke alag alag properties hote hai
    console.log(e.key); //jo keys type hogi wh dikhega
    console.log(e.code) // is a property that represents the physical location of the key on the keyboard, 
                        //rather than the character generated by pressing the key
})

h1.addEventListener('keyup', (e) =>{
    // A keyup event is an event that is triggered when a key on the keyboard is released after being pressed.
    //alag event ke alag alag properties hote hai
    console.log(e.key); //jo keys type hogi wh dikhega
    console.log(e.code) // is a property that represents the physical location of the key on the keyboard, 
                        //rather than the character generated by pressing the key
    // isme shift jb type ho wh bhi dikhta hai
    //isme alt bhi dikhta hai
})

h1.addEventListener('keydown', (e) =>{
    // A keyup event is an event that is triggered when a key on the keyboard is released after being pressed.
    //alag event ke alag alag properties hote hai
    console.log(e.key); //jo keys type hogi wh dikhega
    console.log(e.code) // is a property that represents the physical location of the key on the keyboard, 
                        //rather than the character generated by pressing the key
    // isme shift jb type ho wh bhi dikhta hai
    //isme alt bhi dikhta hai
})

//difference between keyup and keydown

// keydown event: This event occurs when a key on the keyboard is pressed down. 
//It triggers immediately when the key is pressed before the key is actually registered by the system.
// This means that if you hold down a key, the keydown event will fire repeatedly.

// keyup event: Conversely, the keyup event is triggered when a key on the keyboard is released after being pressed. 
// It occurs after the key has been pressed and then released.
